language: node_js
node_js:
  - node
cache:
  directories:
    - '$HOME/.npm'
script:
  - npm run style
  - npm run lint
  - npm run coverage
  - npm run build

after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
